service: vrm-form-service-sls
plugins:
  - serverless-pseudo-parameters
# app and org for use with dashboard.serverless.com
app: form-service
org: edriving

provider:
  name: aws
  runtime: nodejs12.x
  apiKeys:
    - form-service-${opt:stage}
  environment:
    table_name: ${output::${param:env}::vrm-form-service-database-sls.table_name}
    table_region: ${output::${param:env}::vrm-form-service-database-sls.table_region}

  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:*:*:table/${output::${param:env}::vrm-form-service-database-sls.table_name}

  region: eu-west-2
  
functions:
  formServiceSLS:
    handler: index.handler
    events:
      - http:
          path: form-service-sls/structure
          method: any
